- hosts: 127.0.0.1
  connection: local
  user: vagrant
  sudo: yes
  roles:
    - common
  vars_files:
    - roles/common/vars/timezone.yml
    - roles/common/vars/php_fpm.yml
    - roles/common/vars/ganglia.yml
    - roles/common/vars/monit.yml
