- name: enable ip forwarding for lxc
  sysctl: name=net.ipv4.ip_forward value=1 state=present

- name: install dependent packages to build lxc
  yum: name={{ item }} state=present
  with_items:
    - libcap-devel
    - pkgconfig
    - rpm-build
    - docbook2X
    - dnsmasq
    - bridge-utils
    - dpkg
    - debootstrap

- name: download lxc source
  get_url: >
    url=http://lxc.sourceforge.net/download/lxc/lxc-{{ lxc_version }}.tar.gz
    dest=/usr/local/src/lxc-{{ lxc_version }}.tar.gz
    sha256sum={{ lxc_tarball_sha256sum }}

- name: unpack lxc source
  command: >
    creates=/usr/local/src/lxc-{{ lxc_version }}
    tar xf /usr/local/src/lxc-{{ lxc_version }}.tar.gz -C /usr/local/src

- name: configure lxc source
  command: >
    creates=/usr/local/src/lxc-{{ lxc_version }}/config.status
    chdir=/usr/local/src/lxc-{{ lxc_version }}
    ./configure

- name: build lxc source
  command: >
    creates=/root/rpmbuild/RPMS/x86_64/lxc-{{ lxc_version }}-1.el6.x86_64.rpm
    chdir=/usr/local/src/lxc-{{ lxc_version }}
    make rpm

- name: check lxc-libs is installed
  shell: rpm -q lxc-libs > /dev/null; echo $?
  register: result

- name: install lxc-libs
  command: |
    rpm -i /root/rpmbuild/RPMS/x86_64/lxc-libs-{{ lxc_version }}-1.el6.x86_64.rpm
  when: result.stdout != '0'

- name: check lxc is installed
  shell: rpm -q lxc > /dev/null; echo $?
  register: result

- name: install lxc
  command: |
    rpm -i /root/rpmbuild/RPMS/x86_64/lxc-{{ lxc_version }}-1.el6.x86_64.rpm
  when: result.stdout != '0'

- name: centos container definition for lxc
  template: >
    src=roles/lxc/templates/centos_lxc.centos.j2
    dest=/usr/share/lxc/templates/lxc-centos
    owner=root
    group=root
    mode=0755

- name: lxc default config directory
  file: >
    path=/etc/lxc
    state=directory
    owner=root
    group=root
    mode=0755

- name: lxc default config
  template: >
    src=roles/lxc/templates/centos_lxc.default.conf.j2
    dest=/etc/lxc/default.conf
    owner=root
    group=root
    mode=0644

- name: dnsmasq main config
  template: >
    src=roles/lxc/templates/centos_lxc.dnsmasq.conf.j2
    dest=/etc/dnsmasq.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart dnsmasq

- name: lxc dnsmasq config
  template: >
    src=roles/lxc/templates/centos_lxc.dnsmasq.lxc.conf.j2
    dest=/etc/dnsmasq.d/lxc.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart dnsmasq

- name: dnsmasq service
  service: name=dnsmasq state=started enabled=yes

- name: lxc dhclient config
  template: >
    src=roles/lxc/templates/centos_lxc.dhclient-eth0.conf.j2
    dest=/etc/dhcp/dhclient-eth0.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart network

- name: lxc run directory
  file: >
    path=/var/run/lxc
    state=directory
    owner=root
    group=root
    mode=0755

- name: lxc-net config for init script
  template: >
    src=roles/lxc/templates/centos_lxc.lxc-net.sysconfig.j2
    dest=/etc/sysconfig/lxc-net
    owner=root
    group=root
    mode=0644
  notify:
    - restart lxc-net

- name: lxc-net init script
  template: >
    src=roles/lxc/templates/centos_lxc.lxc-net.init.j2
    dest=/etc/init.d/lxc-net
    owner=root
    group=root
    mode=0755
  notify:
    - restart lxc-net

- name: lxc-net service
  service: name=lxc-net state=started enabled=yes

- name: lxc auto config directory
  file: >
    path=/etc/lxc/auto
    state=directory
    owner=root
    group=root
    mode=0755

- name: lxc-auto init script
  template: >
    src=roles/lxc/templates/centos_lxc.lxc-auto.init.j2
    dest=/etc/init.d/lxc-auto
    owner=root
    group=root
    mode=0755
  notify:
    - restart lxc-auto

- name: lxc-auto service
  service: name=lxc-auto state=started enabled=yes

- name: cgroup directory for lxc
  file: >
    path=/cgroup
    state=directory
    owner=root
    group=root
    mode=0755

- name: mount cgroup for lxc
  # cannot create subdirectories if opts contains net_prio
  mount: >
    src=/lxc
    name=/cgroup
    fstype=cgroup
    opts="cpuset,ns,cpu,cpuacct,memory,devices,freezer,net_cls,blkio,perf_event"
    dump=0
    passno=0
    state=mounted
