- name: self signed certificate
  shell: |
    hostname=`hostname` &&
    crt_file="/etc/pki/tls/certs/${hostname}.crt" &&
    key_file="/etc/pki/tls/private/${hostname}.key" &&
    crt_and_key_file="/etc/pki/tls/private/${hostname}.crt_and_key" &&
    subject="{{ self_signed_certificate_subject_prefix }}/CN=${hostname}" &&
    openssl req -new -newkey rsa:2048 -sha1 -x509 -nodes \
      -set_serial {{ self_signed_certificate_serial }} \
      -days {{ self_signed_certificate_days }} \
      -subj "$subject" \
      -out "$crt_file" \
      -keyout "$key_file" &&
    cat "$crt_file" "$key_file" >> "$crt_and_key_file" &&
    chmod 400 "$key_file" "$crt_and_key_file"
    creates="/etc/pki/tls/certs/{{ ansible_fqdn }}.crt"
