- name: install php from remi
  yum: name={{ item }} enablerepo=remi
  with_items:
    - php
    - php-devel
    - php-intl
    - php-mbstring
    - php-mysql
    - php-pdo
    - php-pear
    - php-pecl-apc
    - php-process
    - php-soap
    - php-xml
- name: php.ini
  template: src=roles/common/templates/php.ini.j2 dest=/etc/php.ini owner=root group=root mode=0644
